[package]
name = "macros"
version.workspace = true
authors.workspace = true
edition.workspace = true


[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
serde.workspace = true